### ISSUE TITLE
Please add option for shortcut On Off

### ISSUE THREAD

**Issue by biji** [user501254/TouchpadIndicator#12]
My mouse is wireless, and usb dongle is always plugged, so auto detection will fail. Please add option for shortcut to turn on/off touchpad manually

thanks

**Comment by user501254** [comment]
@biji 
Is it a wireless mouse with a separate dongle or does it rely on your PC's bluetooth?

**Comment by user501254** [comment]
Duplicate of https://github.com/user501254/TouchpadIndicator/issues/23
