### ISSUE TITLE
feature request: bluetooth mouse

### ISSUE THREAD

**Issue by alexemilberg** [user501254/TouchpadIndicator#15]
I have a microsoft designer bluetooth mouse, and touchpad indicator doesnt register when i turn the mouse on and off. But it is listed in the "Exclude mouse device from autodetection" list. does anyone have similar problems with other bluetooth mouses?

**Comment by GenaBitu** [comment]
Isn't that the desired behaviour? What were you expecting to happen?

**Comment by alexemilberg** [comment]
I expect the touchpad to get enabled when i shut off the bluetooth mouse, and vice versa?

**Comment by GenaBitu** [comment]
Oh, sorry, I misread your initial comment - I thought you have checked it to be excluded (in which case it would make sense for it not to work...)
Also, I am in no way affiliated with this extension...

**Comment by user501254** [comment]
@alexemilberg
Could you tell me the model number you are using and if the mouse has a receiver that plug in into your USB port?

**Comment by alexemilberg** [comment]
@user501254 Dont know if this is the model number, 7N5-00003, but its the only thing i could get. There is no text on the mouse what so ever. It uses my laptops internal bluetooth, not any kind of dongle or usb reciever.

https://www.microsoft.com/accessories/en-gb/products/mice/designer-bluetooth-mouse/7n5-00003

**Comment by user501254** [comment]
Duplicate of https://github.com/user501254/TouchpadIndicator/issues/13
