### ISSUE TITLE
Auto disable touch pad after waking from suspension not working. 

### ISSUE THREAD

**Issue by PeaceAlways** [user501254/TouchpadIndicator#16]
I am Arch Linux user with latest Gnome 3.24. The exact problem is whenever my laptop awakes from suspension extension does not detects that the mouse is already connected to my laptop. That's why it does not disables the touch pad.

Apart from this whenever the system reboots the extension works perfect.

**Comment by user501254** [comment]
Hi @PeaceAlways,
Can you confirm if you are using Wayland or X.Org?

**Comment by user501254** [comment]
https://github.com/user501254/TouchpadIndicator/issues/9
