### ISSUE TITLE
Not working with lenovo y700 touch pad.

### ISSUE THREAD

**Issue by Maksim112** [user501254/TouchpadIndicator#19]

**Comment by user501254** [comment]
@Maksim112 
Could you be more clear on what is exactly not working?
If auto disable functionality is not working, try changing the **_"Switch Method"_** under _General_ tab of the extension settings. Also make sure that the **_"Automatically switch Touchpad On/Off"_** is enabled under _Auto Switch_ tab of the extension settings.
