### ISSUE TITLE
Logging loop floods syslog

### ISSUE THREAD

**Issue by JPvRiel** [user501254/TouchpadIndicator#2]
Given this fork has the more recent commits, I assume it's more active and issues should be reported here? I reported the following in the other orangeshirt repo: [Logging loop floods syslog](https://github.com/orangeshirt/gnome-shell-extension-touchpad-indicator/issues/57)

**Comment by user501254** [comment]
Hi @JPvRiel, sorry I can't help you with this particular issue since I am not sure what's wrong here.
I maintain this fork so that it is made compatible with new GNOME Shell releases and user submitted patches can be actively merged into the project. I do not actively develop it.

If you (or anyone else) gets a working fix for the issue, please generate a PR. I will be happy to merge it.

**Comment by JPvRiel** [comment]
Thanks, unfortunately my guess is it's several bugs piling on top of each other... specific touchpad driver bug + journald/syslog dup message filter bug/limitation along with gnome-shell extension logging underneath this. A fix/PR to touchpad indicator would at least not flood syslog.

I 
```
```

**Comment by nigelterry** [comment]
I have the same / similar problem using a Bluetooth mouse on an HP Pavilion running Fedora23. If there is any further information I can provide to help diagnose a fix, please let me know:

Gnome Shell Version: 3.18.5
Touchpad Indicator Version: 25
Touchpad(s): SynPS/2 Synaptics TouchPad
Synclient: Not found or used on your system.
Xinput: Is installed.
Switch Method: Gconf

**Comment by JPvRiel** [comment]
My gnome environment died again today with /var/log filled up by this flooding bug. I haven't had time to dig into the extension's source and find the root cause. However, some mitigating tricks are:
- use a seperate partion for /var/log to avoid the root FS being filled
- try apply rate limiting with rsyslog

In `/etc/rsyslog.d/02-rate_limit.conf`, i'm attempting the following
```
$SystemLogRateLimitInterval 5
$SystemLogRateLimitBurst 100
```

Hopefully that will help throttle how quickly the bug can crash gnome (and the whole system if you don't have a seperate /var/log)

**Comment by user501254** [comment]
Please let me know if this continues to happen with the latest [v33](https://github.com/user501254/TouchpadIndicator/releases/tag/TouchpadIndicator-extensions.gnome.org-v33) release.
