### ISSUE TITLE
Automatic switching of touchpad doesn't work

### ISSUE THREAD

**Issue by GenaBitu** [user501254/TouchpadIndicator#20]
I have a Lenovo Thinkpad T460 and several weeks (maybe even a couple of months) ago the automatic switching off of touchpad ceased working. The mouse is detected (notification shown and icon changed) but the touchpad still works.

I am on debian testing. I can give you some more info if you tell me what you need.

**Comment by user501254** [comment]
@GenaBitu 
Have you tried after changing the **_"Switch Method"_** under _General_ tab of the extension settings?
Also make sure that the **_"Automatically switch Touchpad On/Off"_** is enabled under _Auto Switch_ tab of the extension settings.

**Comment by GenaBitu** [comment]
Oh, OK, 
switching method `synclient` works for me. Probably some change in debian code after work began on buster...

By the way, isn't there a way for the extension to detect this automatically? Would be really nice...

Thank you for your time and this awesome extension, you can close this issue now.

**Comment by user501254** [comment]
Thanks for the suggestion will work on it in a future release.
