### ISSUE TITLE
Disable the touchpad based on mouse movement

### ISSUE THREAD

**Issue by piegamesde** [user501254/TouchpadIndicator#24]
I'd like to have it that the touchpad gets disabled automatically if I move my mouse until it hasn't been used for a while, say a minute or so.

The default solution doesn't work for me since I use a laptop with a wireless mouse. Even if I don't use my mouse, the dongle is always plugged in, keeping my touchpad disabled.

**Comment by john-2000** [comment]
This is similar to the enhancement to have a shortcut switch (which might be more universally applicable).
But great idea!!

**Comment by user501254** [comment]
This will add a lot of complexity which I do not want to deal with right now.
I am in favour of adding a keyboard shortcut to toggle the touchpad as described in another issue, see: https://github.com/user501254/TouchpadIndicator/issues/23#issuecomment-504754287
