### ISSUE TITLE
touchpad works, but takes about 4 mins to activate on first login.

### ISSUE THREAD

**Issue by hdawg12** [user501254/TouchpadIndicator#32]
the touchpad works great when I have my mouse plugged in and then unplug it.  The touchpadindicator automatically swtiches to to touchpad with no issues.  The only problem I'm having is when I don't have my mouse plugged in on startup.  The touchpad takes about 4 mins to start working.  I'm not sure why it does this, but anytime I don't start up my laptop with my mouse plugged in, The touchpad takes a long time to start working.  Can someone help me with this?  I have Kali Linux Rolling and a Acer Aspire E15 laptop.

**Comment by hdawg12** [comment]
does anyone have a fix for this?

**Comment by user501254** [comment]
Hi, I doubt that this is an extension issue. Could you show me some logs?

**Comment by hdawg12** [comment]
where would it be located.  I know its the touchpad-indicator.log file, but I can't find the location

**Comment by hdawg12** [comment]
here is the debug logs
[touchpad-indicator.log](https://github.com/user501254/TouchpadIndicator/files/2899204/touchpad-indicator.log)
let me know what the issue is and how I can fix it.  I timed how long it takes for my touchpad to function when using "Touchpad Indicator".  I takes around 2:48 everytime I log into my kali linux Rolling.

**Comment by user501254** [comment]
If you take a look at the timestamps in the log file, there is no delay for the extension.
This could be a driver issue. Anything in the system journal?

**Comment by hdawg12** [comment]
where do I go to access the system journal?

what driver should I look at?

**Comment by hdawg12** [comment]
are you talking about the touchpad driver?

**Comment by AbdulRaHMaN02** [comment]
i have this problem too pls any one can help me with this

**Comment by AbdulRaHMaN02** [comment]
@hdawg12 
did you found a fix for this yet ??

**Comment by AbdulRaHMaN02** [comment]
Here is the solution:

1. Run the following command in terminal:
sudo gedit /etc/default/grub

2. The GRUB configuration file should open. Locate the following line:
GRUB_CMDLINE_LINUX=" "

3. Add this into the parameters:
i8042.nomux=1 locale=fr_FR i8042.reset

4. The final line should look like this:
GRUB_CMDLINE_LINUX="i8042.nomux=1 locale=fr_FR i8042.reset"

5. Save the file and exit gedit.

6. Run the following command in terminal:
sudo update-grub

7. Let the grub.conf file get recreated, and then restart.

**Comment by hdawg12** [comment]
> Here is the solution:
> 
>     1. Run the following command in terminal:
>        sudo gedit /etc/default/grub
> 
>     2. The GRUB configuration file should open. Locate the following line:
>        GRUB_CMDLINE_LINUX=" "
> 
>     3. Add this into the parameters:
>        i8042.nomux=1 locale=fr_FR i8042.reset
> 
>     4. The final line should look like this:
>        GRUB_CMDLINE_LINUX="i8042.nomux=1 locale=fr_FR i8042.reset"
> 
>     5. Save the file and exit gedit.
> 
>     6. Run the following command in terminal:
>        sudo update-grub
> 
>     7. Let the grub.conf file get recreated, and then restart.

I will try this and let you know how it goes

**Comment by hdawg12** [comment]
> Here is the solution:
> 
>     1. Run the following command in terminal:
>        sudo gedit /etc/default/grub
> 
>     2. The GRUB configuration file should open. Locate the following line:
>        GRUB_CMDLINE_LINUX=" "
> 
>     3. Add this into the parameters:
>        i8042.nomux=1 locale=fr_FR i8042.reset
> 
>     4. The final line should look like this:
>        GRUB_CMDLINE_LINUX="i8042.nomux=1 locale=fr_FR i8042.reset"
> 
>     5. Save the file and exit gedit.
> 
>     6. Run the following command in terminal:
>        sudo update-grub
> 
>     7. Let the grub.conf file get recreated, and then restart.

I tried this and it didn't work.

**Comment by hdawg12** [comment]
It takes about 3 mins for my touchpad to work

**Comment by hdawg12** [comment]
what I also noticed is that when I have my mouse plugged in before I turn on my laptop, it works fine, but when I try my touchpad(while having my mouse usb plugged in) it still works and isn't disabled. So I have the touchpad and mouse working at the same time.  When I unplug my usb mouse, and plug it in again, the notification lets me know that my mouse is plugged in and the touchpad disabled, but the touchpad still works.

**Comment by hdawg12** [comment]
anyone else know what could be causing this issue?

**Comment by AbdulRaHMaN02** [comment]
I don't know but i tried this and worked for me 👻

**Comment by AbdulRaHMaN02** [comment]
The notice above 
That was happening to me to but it solved now 
The same problem to you was for me

**Comment by hdawg12** [comment]
do you know why it isn't working for me?

**Comment by AbdulRaHMaN02** [comment]
i'm sorry , i don't

**Comment by hdawg12** [comment]
I got it to work.  thanks
