### ISSUE TITLE
Gnome 3.32 support

### ISSUE THREAD

**Issue by pointhi** [user501254/TouchpadIndicator#33]
TouchpadIndicator-extensions.gnome.org-v32 is tagged but not visible in https://extensions.gnome.org/extension/131/touchpad-indicator/

**Comment by user501254** [comment]
As of today, that [tag](https://github.com/user501254/TouchpadIndicator/releases/tag/TouchpadIndicator-extensions.gnome.org-v32) is pending review on [the GNOME extensions website](https://extensions.gnome.org/review/9186).
It's pretty down in the [list](https://extensions.gnome.org/review/), so I am not sure when it will be active.
