### ISSUE TITLE
GS 3.32 - TypeError: PopupMenu.PopupSwitchMenuItem.prototype._init is undefined

### ISSUE THREAD

**Issue by luca-viggiani** [user501254/TouchpadIndicator#34]
Hi, I'm testing lates version from GitHub on GS 3.32 on Arch Linux and I get the following error (as shown by looking-glass):

`PopupMenu.PopupSwitchMenuItem.prototype._init is undefined`

Here are my debug info:
```
Versione di GNOME shell: 3.32.0
Versione di Touchpad Indicator: 32
Touchpad: SynPS/2 Synaptics TouchPad | DLL075B:01 06CB:76AF Touchpad
Synclient: Non trovato o utilizzato nel sistema.
Xinput: Not found on your system.
Switch Method: Gconf
```
I'm on a Wayland session
Cheers

**Comment by user501254** [comment]
There are a number of issues when using the extension on Wayland. Have you tried it on the X system as well? Does it give the same error?

I haven't fully tested support for gnome shell 3.32. I really wanted the extension version to match the shell release version.

**Comment by luca-viggiani** [comment]
No yet, I'm going to test it now. However, I've been using the extension on Wayland and Gnome 3.30 without any problems for long time.

**Comment by luca-viggiani** [comment]
Ok tested on X11 right now, same error. :(

**Comment by user501254** [comment]
Okay, it's due to the recent changes introduced in https://github.com/GNOME/gnome-shell/commit/bacfdbbb0338b94295c64093523bca7ba8d5c5ca.
Will try to make the required changes over the weekend. 
Thank you for reporting!

**Comment by luca-viggiani** [comment]
Great thanks!

Il lun 18 mar 2019, 19:58 Ashesh Singh <notifications@github.com> ha
scritto:

**Comment by user501254** [comment]
Adding details of the error.

https://github.com/user501254/TouchpadIndicator/blob/af6fb8a61000f8a5e9bb4032819f46fbb8abcfb0/extension.js#L257

```
Apr 04 14:33:22 ubuntu gnome-shell[1827]: JS WARNING: [/home/ubuntu/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/extension.js 257]: reference to undefined property "_init"
Apr 04 14:33:22 ubuntu gnome-shell[1827]: Extension "touchpad-indicator@orangeshirt" had error: TypeError: PopupMenu.PopupSwitchMenuItem.prototype._init is undefined
```

**Comment by user501254** [comment]
Hi, just wanted to update you that all `Lang.Class` definitions will have to be updated to the new ES6 syntax as a result of [upstream changes](https://gitlab.gnome.org/GNOME/gnome-shell/commit/bacfdbbb0338b94295c64093523bca7ba8d5c5ca). This will take considerably more time to accomplish.

**Comment by user501254** [comment]
@luca-viggiani Please check if the current [master](https://github.com/user501254/TouchpadIndicator/tree/master) works for you. Let me know in case of any issues.

**Comment by luca-viggiani** [comment]
Thanks!


*Luca Viggiani*
*CTO and QMS*Grammelot Srl
Via Copernico, 38
20125 Milano

T: +39 02 89075413
F: +39 02 32066978
M: +39 340 3627802
Skype: gorgonilla
 Please consider the environment before printing this e-mail.
This email and any attachments are confidential to the intended recipient
and may also be privileged. If you are not the intended recipient please
delete it from your system and notify the sender. You should not copy it or
use it for any purpose nor disclose or distribute its contents to any other
person. Any improper use of this email and its attachments will lead to the
person responsible having to deal with all the associated civil and
criminal consequences of their actions (EU Regulation 2016/679). The sender
shall not be liable for the improper or incomplete transmission of the
information contained in this communication nor for any delay in its
receipt or damage to your system. The sender does not guarantee that the
integrity of this communication has been maintained nor that this
communication is free of viruses, interceptions or interference.
About GDPR: the recipient receives this e-mail because gave us his data
personally or through a digital media expressing his explicit authorization
to use them. We encourage you to review our Privacy Policy and Data
Protection Policy <https://www.grammelot.eu/GDPR_PrivacyPolicy.pdf>. If you
have any questions, please contact us at privacy@grammelot.eu.


Il giorno dom 23 giu 2019 alle ore 14:25 Ashesh Singh <
notifications@github.com> ha scritto:

**Comment by user501254** [comment]
Fixed under [v33](https://github.com/user501254/TouchpadIndicator/releases/tag/TouchpadIndicator-extensions.gnome.org-v33).
