### ISSUE TITLE
Error: Expected type utf8 for Argument 'domain' but got type 'undefined'

### ISSUE THREAD

**Issue by goberhammer** [user501254/TouchpadIndicator#37]
Installed the latest version from extensions.gnome.org. Got this error on log:

gnome-software[3453]: touchpad-indicator_orangeshirt has error: Error: Expected type utf8 for Argument 'domain' but got type 'undefined'

Ubuntu 19.04

**Comment by user501254** [comment]
Hi, I haven't uploaded the newest version on the Gnome Extensions website. Please checkout the master branch on GitHub.
