### ISSUE TITLE
Doesn't work in GNOME-Shell 3.34.1

### ISSUE THREAD

**Issue by antosamalona** [user501254/TouchpadIndicator#38]
Why is it not working on GNOME-Shell 3.34.1?

**Comment by user501254** [comment]
It's not supposed yet.

**Comment by antosamalona** [comment]
Is it still development?

**Comment by user501254** [comment]
What's the error that you are getting? Some logs would be nice too.
I haven't started work on the new version yet. But you are welcome to make a pull request.

**Comment by antosamalona** [comment]
It doesn't work in my gnome v 3.34

**Comment by user501254** [comment]
Understood.
Please try to follow [this link](https://askubuntu.com/a/1108266/269515) and report back the error messages.

**Comment by Golvanig** [comment]
Hello,
Here is the information from my linux instance:

- Extension Touchpad Indicator: 2019-10-29T14:27:40Z    touchpadIndicatorButton._init(): Can`t find Xinput
- Extension "touchpad-indicator@orangeshirt" had error: TypeError: GObject_Object.prototype._init called on incompatible Object
- gnome-software[2681]: State change on user/*/*/shell-extension/touchpad-indicator_orangeshirt/* from available to installed is not OK
- gnome-software[2681]: touchpad-indicator_orangeshirt has error: TypeError: GObject_Object.prototype._init called on incompatible Object
- gnome-software[2681]: touchpad-indicator_orangeshirt has error: TypeError: GObject_Object.prototype._init called on incompatible Object

With "latest Debian bullseye" and gnome 3.34.1.

Thanks for your very convenient tool :)

**Comment by user501254** [comment]
Thank you. However, I am unable to observe these errors in my setup. Please make sure that you are using the current [master](https://github.com/user501254/TouchpadIndicator/tree/master) branch and not the one available on extensions.gnome.org.

**Comment by mdugas** [comment]
@user501254 According to lookingglass comp[1] is undefined

![image](https://user-images.githubusercontent.com/2657852/68606885-69c28400-047d-11ea-9d73-12d51a6bbe37.png)

Also by opening the properties of the extension in gnome tweaks, we can find this stack trace.

```
TypeError: comp[1] is undefined

Stack trace:
  _listPointingDevices@/home/kronus/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/xinput.js:60:13
  _init@/home/kronus/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/xinput.js:42:32
  XInput@/home/kronus/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/xinput.js:37:9
  TouchpadIndicatorSettings@/home/kronus/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/prefs.js:44:22
  buildPrefsWidget@/home/kronus/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/prefs.js:239:20
  _showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:57:22
  _extensionsLoaded@resource:///org/gnome/shell/extensionPrefs/main.js:320:13
  _scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:298:13
  asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:132:13
  main@resource:///org/gnome/shell/extensionPrefs/main.js:707:5
  @<main>:1:43
```

**Comment by mdugas** [comment]
After looking at the source, I found that xinput is a required software package. On Manjaro, it isn't installed by default.

@Golvanig you can try installing the package with `apt-get install xinput` and reload gnome (alt+f2, type r and press enter) to see if the extension loads. For those following a trail to this and use Manjaro, use `pacman -S xorg-xinput`

**Comment by jankatins** [comment]
This is left in my systemd journal if I deinstall and then install touchpad indicator (debian unstable, just freshly updated): 
```
Nov 11 22:14:13 littlebottom2 gnome-shell[2536]: Usage of object.actor is deprecated for TouchpadIndicator.TouchpadIndicator
                                                 get@resource:///org/gnome/shell/ui/environment.js:249:29
                                                 _init@/home/js/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/extension.js:274:9
                                                 wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                 enable@/home/js/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/extension.js:923:25
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:131:13
                                                 loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21
                                                 callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:17
                                                 gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
Nov 11 22:14:13 littlebottom2 gnome-shell[2536]: JS ERROR: Extension touchpad-indicator@orangeshirt: Error: GSettings key first-time not found in schema org.gnome.shell.extensions.touchpad-indicator
                                                 _checkKey@resource:///org/gnome/gjs/modules/overrides/Gio.js:563:23
                                                 _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:528:13
                                                 _loadConfig@/home/js/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/extension.js:387:32
                                                 wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                 _init@/home/js/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/extension.js:278:9
                                                 wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                 enable@/home/js/.local/share/gnome-shell/extensions/touchpad-indicator@orangeshirt/extension.js:923:25
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:131:13
                                                 loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21
                                                 callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:17
                                                 gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
```

**Comment by user501254** [comment]
The extension should work on Gnome 3.34 if it was working on Gnome 3.32.

@mdugas is right, `xinput` is required for the extension to function. Try running `xinput --list` and see if you get any output. 
Also what's the version of the extension in use here?

**Comment by antosamalona** [comment]
It works after I installed xinput. Thank you!
