### ISSUE TITLE
Switch Method: Gconf doesn't worked

### ISSUE THREAD

**Issue by pointhi** [user501254/TouchpadIndicator#4]
Probably releated to: https://github.com/orangeshirt/gnome-shell-extension-touchpad-indicator/issues/43

When using the default Switch Method, the touchpad is not going to be disabled. On the other hand, using ```Synclient``` or ```XInput``` worked without problem.

(I'm using Antergos, with Gnome 3.20)

**Comment by user501254** [comment]
Hi @pointhi 
I didn't face this issue with any of the machines on which I have used this extension. You could always set your preferred/working switching method under the extension's settings. This has to be done only once after you install the extension so I suppose it's no big deal.
However if others too report this issue, I could always set `xinput` as the default switching method.

**Comment by neclimdul** [comment]
Was struggling with getting the extension to work and finally found this. Changing the switch method fixed it for me as well. 

Ubuntu Gnome 16.06 which is also Gnome 3.20 so a change in 3.20 might be the culprit.

**Comment by user501254** [comment]
@neclimdul 
Thank you for reporting. 
Next version will have `xinput` as the default switching method.
