### ISSUE TITLE
Disconnect Bluetooth Mouse not Reenabling Touchpad

### ISSUE THREAD

**Issue by lvlanson** [user501254/TouchpadIndicator#47]
When disconnecting a bluetooth mouse (Logitech Anywhere 2s) Touchpad Indicator does not snap back to the touchpad mouse.

**Comment by user501254** [comment]
When you say "disconnect" do you mean that the dongle (USB bluetooth adapter) is unplugged?

**Comment by lvlanson** [comment]
There is no bluetooth dongle attached to the notebook. The notebook uses its own bluetooth device.
If I switch off bluetooth, disconnect the mouse via the laptop or switch off the mouse itself, touch pad indicator does not snap back to touchpad mode.

**Comment by user501254** [comment]
Okay, got it. Have you tried using the keyboard shortcut (<kbd><kbd>Ctrl</kbd> + <kbd>Super</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd></kbd>)?
The extension is not designed to work with in-built bluetooth devices.

That being said, I can try to make it compatible. Please tell me a bit more about the setup, I need:
1. Extension version
2. Switching method in use
3. Gnome shell version
4. At least `N: Name=` and `P: Phys=` lines from output for `cat /proc/bus/input/devices`
5. Logs from the extension

**Comment by lvlanson** [comment]
1. Gnome Extension Version: 3.34.3
2. Switching Method: Disconnecting Bluetooth
3. Gnome Shell Version: 3.34.3
4. 
I: Bus=0005 Vendor=046d Product=b01a Version=0003
N: Name="MX Anywhere 2S Keyboard"
P: Phys=D4:3B:04:9E:89:18
S: Sysfs=/devices/virtual/misc/uhid/0005:046D:B01A.0001/input/input15
U: Uniq=E5:00:B5:38:66:EB
H: Handlers=sysrq kbd event14 
B: PROP=0
B: EV=100013
B: KEY=1000000000007 ff800000000007ff febeffdfffefffff fffffffffffffffe
B: MSC=10

I: Bus=0005 Vendor=046d Product=b01a Version=0003
N: Name="MX Anywhere 2S Mouse"
P: Phys=D4:3B:04:9E:89:18
S: Sysfs=/devices/virtual/misc/uhid/0005:046D:B01A.0001/input/input16
U: Uniq=E5:00:B5:38:66:EB
H: Handlers=mouse2 event15 
B: PROP=0
B: EV=17
B: KEY=ffff0000 0 0 0 0
B: REL=1943
B: MSC=10
[touchpad-indicator.log](https://github.com/user501254/TouchpadIndicator/files/4261116/touchpad-indicator.log)
5. Attached File

**Comment by user501254** [comment]
I am getting a similar mouse with in-built bluetooth (ie. no usb dongle). I guess the extension can watch the state of currently connected bluetooth devices to detect disconnects and enable/disable the touchpad accordingly.

**Comment by user501254** [comment]
I verified this with the new hardware.
When you disconnect the mouse (ie, toggle the hardware switch to 'off'), it should immediately be picked up by the laptop's Bluetooth. If that's not the case, it's and issue outside the extension's control.
You can always you the toggle keys <kbd><kbd>Ctrl</kbd> + <kbd>Super</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd></kbd> to force enable/disable the touchpad.
