### ISSUE TITLE
When I active, can't login to ubuntu on wayland

### ISSUE THREAD

**Issue by secondstriker** [user501254/TouchpadIndicator#53]
**Describe the issue**  
A clear and concise description of what the issue is.
When I active extension in Xorg, then I can't log in to Ubuntu Wayland.
I disabled and enabled all of my extensions one by one to catch this.

---
**Mandatory system details** (please complete/update the following information)
 - **Operating System:** Ubuntu 20.04 LTS
 - **Touchpad Indicator extension version:** 35
 - **Gnome Shell version:** GNOME Shell 3.36.2
 - **Display server:** X11 or Wayland
 - **Switching method:** GSetting or Xinput or Synclient
 - **Installation source:** [extensions.gnome.org](https://extensions.gnome.org/extension/131/touchpad-indicator/) or [GitHub repository](https://github.com/user501254/TouchpadIndicator)

**Comment by user501254** [comment]
Hi, I can't reproduce this.
Try installing `xinput` and see if that changes anything.

If that doesn't work, feel free to reopen the issue with all the required details from the issue template.
