### ISSUE TITLE
Show/hide switch icon not working

### ISSUE THREAD

**Issue by odimn** [user501254/TouchpadIndicator#56]
Hello! Thumbs up for this extension! Very nice work!
 In extension settings the Show Icon switch does nothing.

---
**Expected behavior**  
Clicking the switch, the icon indicator in top panel disappears.

---
**Steps to reproduce the behavior**
1. Right click on TouchpadIndicator icon on top panel.
2. Click on 'Indicator Preferences'.
3. Left click on switch 'Show Icon' to disable panel icon.
4. Nothing happens!

---
**Screenshots**

---
**Mandatory system details**
[touchpad-indicator.log](https://github.com/user501254/TouchpadIndicator/files/4833479/touchpad-indicator.log)

 - **Operating System:** Running Manjaro Linux/Build:rolling
 - **Touchpad Indicator extension version:** 36
 - **Gnome Shell version:** GNOME Shell 3.36.2
 - **Display server:** X11
 - **Switching method:** Xinput
 - **Installation source:** https://extensions.gnome.org/extension/131/touchpad-indicator/

 ---
 **Optional details**
 
 - **Input Devices** 
I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="Ideapad extra buttons"
P: Phys=ideapad/input0
S: Sysfs=/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/input/input6
U: Uniq=
H: Handlers=kbd event5 rfkill 
B: PROP=0
B: EV=13
B: KEY=81000800100c03 4400000000300000 0 2
B: MSC=10

I: Bus=0003 Vendor=045e Product=07fd Version=0111
N: Name="Microsoft Microsoft Nano Transceiver 1.1"
P: Phys=usb-0000:00:14.0-1/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.2/0003:045E:07FD.0003/input/input21
U: Uniq=
H: Handlers=event20 mouse1 
B: PROP=0
B: EV=17
B: KEY=1f0000 0 0 0 0
B: REL=903
B: MSC=10

- **X input devices** 
   
   ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
   ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
   ⎜   ↳ Microsoft Microsoft Nano Transceiver 1.1 Consumer Control	id=10	[slave  pointer  (2)]
   ⎜   ↳ Microsoft Microsoft Nano Transceiver 1.1	id=13	[slave  pointer  (2)]
   ⎜   ↳ SynPS/2 Synaptics TouchPad              	id=17	[slave  pointer  (2)]
   ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Microsoft Microsoft Nano Transceiver 1.1	id=9	[slave  keyboard (3)]
    ↳ Microsoft Microsoft Nano Transceiver 1.1 System Control	id=11	[slave  keyboard (3)]
    ↳ Microsoft Microsoft Nano Transceiver 1.1	id=12	[slave  keyboard (3)]
    ↳ Lenovo EasyCamera: Lenovo EasyC         	id=14	[slave  keyboard (3)]
    ↳ Ideapad extra buttons                   	id=15	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=16	[slave  keyboard (3)]

---
**Additional context**  
 From a small  investigation i made in the extensions files, I found out, that inside the file 'extensions.js' in lines:
  285      // Show panel icon if `show-panelicon` is true or at least one of the
  286     // device switches is in the off position.
  287       this.visible = alwaysShow || items.some(s => s.state === false)
if i change "=> s.state === false" to "=> s.state === true"
the function is normal again.
I hope this helped.

Thank you again for this great extension!

**Comment by user501254** [comment]
Hi! Thank you.
Your investigation is correct but this is intentional (see: https://github.com/user501254/TouchpadIndicator/issues/39).
As per current functionality, an icon will always be shown when any of the pointing devices is disabled. This is to prevent unnecessary frustration that my arise by not immediately knowing the state of the pointing device.

You can anyways modify the lines to fit your needs. I hope that helps.

**Comment by odimn** [comment]
Ah, Ok!!
 Thank you for the clarification and your quick answer. Sorry I missed that
post.
Anyways, i commend you could remove the switch in some update for it serves
no purpose.
I modified the line because i'm trying to de-clutter my panel from the
icons.
Thanks again!
