### ISSUE TITLE
wrong working on Kali Linux 2.0 (based Debian distro)

### ISSUE THREAD

**Issue by scila1996** [user501254/TouchpadIndicator#6]
hello , when i don't plug mouse that touchpad is auto disabled ? if mouse is plug -> touchpad auto disable (work) . But unplug it's still disabled and OS starup -> touchpad auto disabled . I'm tried xinput, gconf, sysclient and .... ?? Please fix it 

Thank you !!

**Comment by user501254** [comment]
It could take a few seconds for the touchpad to be enabled once the mouse has been unplugged. However if the touchpad remains disabled even after a considerable amount of time, I would suggest a resart.

**Comment by user501254** [comment]
Duplicate of https://github.com/user501254/TouchpadIndicator/issues/9
