### ISSUE TITLE
Shortcut key to disable/enable

### ISSUE THREAD

**Issue by richsmith** [user501254/TouchpadIndicator#60]
**Is your feature request related to a problem? Please describe.**
Usually the extension is extremely useful, but it's a bit of an annoyance if the touchpad is auto-disabled when the mouse is unavailable. E.g. bluetooth mouse somewhere in range but misplaced, or taking a while to connect.

**Describe the solution you'd like**
Ideally I'd like some way of re-enabling the touchpad manually. The only way I can think of is with a key combination.

**Comment by talenttickersmith** [comment]
Apologies, it seems this already got added in a previous release. However, the shortcut doesn't seem to work for me. I'd also suggest adding the shortcut details to the readme or the touchpad settings.

**Comment by user501254** [comment]
If open touchpad settings, it does show the shortcut key but I will also include it in the README at some point.
The shortcut should work unless the same key combination is used by some other application/system. You may try changing the shortcut as described in this comment: https://github.com/user501254/TouchpadIndicator/issues/23#issuecomment-504754287.
