### ISSUE TITLE
It isn't re-activate touchpad

### ISSUE THREAD

**Issue by wolkzel** [user501254/TouchpadIndicator#63]
I started to use this app on Pop!_Os, it definitely deactivate the touchpad when I plug in my mouse but after I'm removing it, app doesn't reactivate my touchpad.

**Comment by user501254** [comment]
Please follow the issue template when opening new issues.
Your issue discription tells me absolutely nothing about your setup. Also please have a look at other issues which may match your description (eg. https://github.com/user501254/TouchpadIndicator/issues/61).
